// This file contains the static data for the app.
// In a real application, this data would likely be fetched from a database.

export const allDishes = [
    {
      id: '1',
      name: 'Spaghetti Carbonara',
      cook: 'Chef Isabella',
      rating: 4.9,
      reviews: 132,
      price: '18.50',
      image: 'https://placehold.co/600x400.png',
      hint: 'pasta italian food',
      tags: ['Italian', 'Classic'],
      distance: 2.5,
      description: "A classic Roman pasta dish with creamy egg sauce, pancetta, and pecorino cheese.",
      chefDescription: "Experience a true taste of Rome with my authentic Carbonara. I use only traditional guanciale, fresh eggs from a local farm, and Pecorino Romano, tossed with spaghetti cooked to perfect al dente. It's a simple dish, but one where quality makes all the difference. This is the recipe my nonna taught me, and it's a plate full of love.",
    },
    {
      id: '2',
      name: 'Gourmet Burger & Fries',
      cook: 'Grillmaster Joe',
      rating: 4.8,
      reviews: 98,
      price: '22.00',
      image: 'https://placehold.co/600x400.png',
      hint: 'burger fries',
      tags: ['American', 'Comfort Food'],
      distance: 1.8,
      description: "A juicy, handcrafted burger with all the classic fixings and a side of crispy, golden fries.",
      chefDescription: "This isn't just a burger; it's the culmination of my quest for the perfect patty. I grind my own blend of brisket and chuck for a rich, beefy flavor, sear it on a cast-iron skillet for that unbeatable crust, and nestle it in a toasted brioche bun with sharp cheddar, crisp lettuce, and my secret sauce. Get ready for the best burger of your life.",
    },
    {
      id: '3',
      name: 'Fresh Salmon Poke Bowl',
      cook: 'Sushi Sensei Kenji',
      rating: 4.9,
      reviews: 150,
      price: '19.75',
      image: 'https://placehold.co/600x400.png',
      hint: 'poke bowl healthy',
      tags: ['Healthy', 'Hawaiian'],
      distance: 3.2,
      description: "A vibrant and healthy bowl of sushi rice, fresh salmon, avocado, and various delicious toppings.",
      chefDescription: "Let me transport you to the shores of Hawaii. I start with perfectly seasoned sushi rice and top it with glistening, sushi-grade salmon, creamy avocado, crunchy cucumber, and sweet edamame. A drizzle of my signature shoyu-based sauce and a sprinkle of sesame seeds completes this refreshing and utterly satisfying meal.",
    },
    {
      id: '4',
      name: 'Vegan Pad Thai',
      cook: 'Plant-based Queen Anya',
      rating: 4.7,
      reviews: 85,
      price: '16.50',
      image: 'https://placehold.co/600x400.png',
      hint: 'pad thai vegan',
      tags: ['Vegan', 'Thai'],
      distance: 4.5,
      description: "A delicious plant-based take on the classic Thai noodle dish, full of flavor and fresh vegetables.",
      chefDescription: "Who says you need meat for an flavor explosion? My Pad Thai is a testament to the power of plants. I stir-fry rice noodles with crispy tofu, fresh bean sprouts, and a colorful array of vegetables in a sweet, sour, and savory tamarind sauce. Topped with crushed peanuts and a wedge of lime, it's a vibrant dish that will delight your senses.",
    },
    {
      id: '5',
      name: 'Margherita Pizza',
      cook: 'Chef Isabella',
      rating: 4.8,
      reviews: 210,
      price: '15.00',
      image: 'https://placehold.co/600x400.png',
      hint: 'pizza italian',
      tags: ['Italian', 'Vegetarian'],
      distance: 2.5,
      description: "Simple and delicious pizza with San Marzano tomatoes, fresh mozzarella, basil, and a drizzle of olive oil.",
      chefDescription: "The Margherita is the queen of pizzas for a reason. My dough is naturally leavened for 72 hours, creating a light, airy crust with a delightful chew. I top it with vibrant San Marzano tomato sauce, creamy fior di latte mozzarella, fresh basil, and a kiss of extra virgin olive oil. It's Italian simplicity at its finest.",
    },
    {
      id: '6',
      name: 'BBQ Pulled Pork Sandwich',
      cook: 'Grillmaster Joe',
      rating: 4.7,
      reviews: 76,
      price: '17.00',
      image: 'https://placehold.co/600x400.png',
      hint: 'bbq sandwich pork',
      tags: ['American', 'BBQ'],
      distance: 1.8,
      description: "Slow-smoked pulled pork, drenched in tangy BBQ sauce, and piled high on a soft brioche bun.",
      chefDescription: "I believe great BBQ takes time, and my pulled pork is no exception. I smoke the pork shoulder low and slow for 12 hours over hickory wood until it's fall-apart tender. Then, I pile it high on a buttery brioche bun and slather it with my homemade tangy and sweet BBQ sauce. Served with a side of coleslaw, it's a taste of the South.",
    },
    {
      id: '7',
      name: 'Tiramisu',
      cook: 'Chef Isabella',
      rating: 4.9,
      reviews: 180,
      price: '9.50',
      image: 'https://placehold.co/600x400.png',
      hint: 'dessert sweet tiramisu',
      tags: ['Dessert', 'Italian'],
      distance: 2.5,
      description: "A beloved Italian dessert with coffee-soaked ladyfingers, mascarpone cream, and a dusting of cocoa.",
      chefDescription: "My Tiramisu is the perfect 'pick-me-up.' I layer delicate, espresso-soaked ladyfingers with a cloud-like cream made from mascarpone and egg yolks. A generous dusting of premium cocoa powder on top provides the perfect bitter balance to the sweetness. It’s an elegant, classic dessert that will leave you dreaming of Italy.",
    },
    {
      id: '8',
      name: 'Chicken Parmesan',
      cook: 'Chef Isabella',
      rating: 4.8,
      reviews: 145,
      price: '22.00',
      image: 'https://placehold.co/600x400.png',
      hint: 'chicken italian parmesan',
      tags: ['Italian', 'Comfort Food'],
      distance: 2.5,
      description: "Breaded chicken breast, fried and topped with marinara sauce and mozzarella, served with pasta.",
      chefDescription: "This is comfort food, elevated. I take a tender chicken breast, coat it in seasoned breadcrumbs, and fry it to golden perfection. Then, it's smothered in my rich, homemade marinara sauce, topped with a generous layer of molten mozzarella and nutty Parmesan, and baked until bubbly. It's a hearty, satisfying classic done right.",
    },
  ];
