# Script para monitorear el estado del build
$repo = "vicholitvak/moai"
$branch = "main"

Write-Output "`n========================================="
Write-Output "📊 MONITOR DE BUILD Y DEPLOY"
Write-Output "=========================================`n"

Write-Output "🔍 Repositorio: $repo"
Write-Output "🌿 Branch: $branch"
Write-Output ""

Write-Output "📍 ENLACES ÚTILES:"
Write-Output "----------------------------------------"
Write-Output "GitHub Actions: https://github.com/$repo/actions"
Write-Output "Vercel Dashboard: https://vercel.com/vicholitvaks-projects/moai-app"
Write-Output "GitHub Secrets: https://github.com/$repo/settings/secrets/actions"
Write-Output ""

Write-Output "⏱️ TIEMPO ESTIMADO:"
Write-Output "----------------------------------------"
Write-Output "GitHub CI/CD: 3-5 minutos"
Write-Output "Vercel Deploy: 2-3 minutos"
Write-Output "Total: ~5-8 minutos"
Write-Output ""

Write-Output "✅ QUÉ BUSCAR EN GITHUB ACTIONS:"
Write-Output "----------------------------------------"
Write-Output "En el paso '🏗️ Build application':"
Write-Output "  ✅ 'Firebase Admin initialized successfully'"
Write-Output "  ✅ 'Compiled successfully'"
Write-Output "  ✅ 'Collecting page data ...'"
Write-Output "  ✅ 'Generating static pages ...'"
Write-Output ""

Write-Output "⚠️ WARNINGS NORMALES (IGNORAR):"
Write-Output "----------------------------------------"
Write-Output "  ⚠ 'Compiled with warnings'"
Write-Output "  ⚠ 'Critical dependency: the request of a dependency is an expression'"
Write-Output "  → Estos son de Prisma/OpenTelemetry, no afectan funcionalidad"
Write-Output ""

Write-Output "❌ ERRORES A EVITAR:"
Write-Output "----------------------------------------"
Write-Output "  ❌ 'Error initializing Firebase Admin'"
Write-Output "  ❌ 'Failed to parse private key'"
Write-Output "  → Si aparecen, verifica los secretos en GitHub"
Write-Output ""

Write-Output "🎯 PRÓXIMOS PASOS:"
Write-Output "----------------------------------------"
Write-Output "1. Espera a que GitHub Actions termine (status verde ✅)"
Write-Output "2. Vercel automáticamente hará deploy"
Write-Output "3. Verifica que la app funcione en producción"
Write-Output ""

Write-Output "🔄 COMANDOS ÚTILES:"
Write-Output "----------------------------------------"
Write-Output "Ver variables Vercel:     vercel env ls production"
Write-Output "Deploy manual a Vercel:   vercel --prod"
Write-Output "Ver logs de Vercel:       vercel logs [deployment-url]"
Write-Output ""

Write-Output "=========================================`n"
Write-Output "💡 TIP: Abre los enlaces arriba para monitorear en tiempo real"
Write-Output "=========================================`n"
