# Script para verificar que los secretos fueron agregados correctamente
Write-Output "`n========================================="
Write-Output "🔐 VERIFICADOR DE SECRETOS DE GITHUB"
Write-Output "=========================================`n"

Write-Output "📋 Secretos que debes haber agregado:"
Write-Output ""
Write-Output "✓ FIREBASE_PROJECT_ID"
Write-Output "✓ FIREBASE_CLIENT_EMAIL"
Write-Output "✓ FIREBASE_PRIVATE_KEY"
Write-Output ""
Write-Output "========================================="
Write-Output "🔄 PRÓXIMO PASO:"
Write-Output "=========================================`n"
Write-Output "1. Ve a: https://github.com/vicholitvak/moai/actions"
Write-Output "2. Busca el workflow que falló (el más reciente con ❌)"
Write-Output "3. Click en 'Re-run all jobs' (botón arriba a la derecha)"
Write-Output "4. Espera unos minutos..."
Write-Output "5. El build debería pasar con ✅"
Write-Output ""
Write-Output "========================================="
Write-Output "✅ LIMPIEZA:"
Write-Output "=========================================`n"
Write-Output "Después de que el build pase, ejecuta:"
Write-Output "  Remove-Item github_private_key.txt -Force"
Write-Output ""
Write-Output "Para eliminar el archivo temporal con la clave.`n"
