import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from '../context/AuthContext';
import { CartProvider } from '../context/CartContext';
import { UserProfileProvider } from '../context/UserProfileContext';
import AuthHandler from '../context/AuthHandler';
import { Toaster } from '../components/ui/sonner';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Moai",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <UserProfileProvider>
            <CartProvider>
              <AuthHandler>{children}</AuthHandler>
              <Toaster />
            </CartProvider>
          </UserProfileProvider>
        </AuthProvider>
      </body>
    </html>
  );
}