// components/ui/toaster.tsx
// This file will be generated by shadcn/ui. I'm creating a placeholder for now.
// You will need to run `npx shadcn-ui add toast` and `npx shadcn-ui add use-toast`
// to generate the actual files.

export function Toaster() {
  return null;
}
